{
  "parameters": {
    "endpoint": "https://remoterendering.eastus.mixedreality.azure.com",
    "api-version": "2021-01-01",
    "account_id": "30ea64bd-100f-4bf0-adc9-29fa45d4880c",
    "session_id": "contoso-session-c2b8ac1d-9494-4852-a59c-8c28813adc28",
    "body": {
      "maxLeaseTimeMinutes": 60,
      "size": "Standard"
    }
  },
  "responses": {
    "201": {
      "headers": {
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      },
      "body": {
        "id": "contoso-session-c2b8ac1d-9494-4852-a59c-8c28813adc28",
        "creationTime": "2020-11-11T11:11:11.111Z",
        "maxLeaseTimeMinutes": 60,
        "size": "Standard",
        "status": "Starting",
        "error": null
      }
    },
    "200": {
      "headers": {
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      },
      "body": {
        "id": "contoso-session-c2b8ac1d-9494-4852-a59c-8c28813adc28",
        "creationTime": "2020-11-11T11:11:11.111Z",
        "maxLeaseTimeMinutes": 60,
        "size": "Standard",
        "status": "Starting",
        "error": null
      }
    },
    "400": {
      "headers": {
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      },
      "body": {
        "error": {
          "code": "BadRequest",
          "message": "The request was malformed."
        }
      }
    },
    "409": {
      "headers": {
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      },
      "body": {
        "error": {
          "code": "Conflict",
          "message": "A resource already exists under the given ID."
        }
      }
    },
    "401": {
      "headers": {
        "WWW-Authenticate": "Bearer error=\"invalid_token\"",
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      }
    },
    "403": {
      "headers": {
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      }
    },
    "429": {
      "headers": {
        "Retry-After": 15,
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      }
    },
    "500": {
      "headers": {
        "MS-CV": "dKEFmka2kkSlDmp/af+sOw"
      },
      "body": {
        "error": {
          "code": "InternalServerError",
          "message": "An internal server error occurred."
        }
      }
    }
  }
}
